---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/darren/jelly/config:/config
      - /home/darren/jelly/series:/data/series
      - /home/darren/jelly/movie:/data/movies
      - /home/darren/jelly/youtube:/data/youtube
      - /home/darren/jelly/audio:/data/audio
    ports:
      - 8096:8096
    restart: unless-stopped
