---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: bass
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/jellyfin/config:/config
      - /fataf/media/series:/data/series
      - /fataf/media/movies:/data/movies
      - /fataf/media/youtube:/data/youtube
      - /fataf/media/books:/data/books
      - /fataf/media/audio:/data/audio
    ports:
      - 1984:8096
    restart: unless-stopped
