---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: bass
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/fin/config:/config
      - /home/fin/series:/data/series
      - /home/fin/movie:/data/movies
      - /home/fin/youtube:/data/youtube
      - /home/fin/audio:/data/audio
    ports:
      - 1984:8096
    restart: unless-stopped
